services:
  dev:
    image: bbsgo-dev:latest
    container_name: bbsgo-dev
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./:/root/bbs-go
    ports:
      - 8080:8080
      - 8082:8082
      - 3000:3000
    network_mode: bridge
  
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
