services:
  dev:
    image: bbsgo-dev:latest
    container_name: bbsgo-dev
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    user: 1000:1000
    volumes:
      - ./:/bbs-go
    environment:
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - 8080:8080
      - 8082:8082
      - 8123:8123
      - 3000:3000
    network_mode: bridge
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb-galera
      - PMA_USER=bbsgo
      - PMA_PASSWORD=123456
